# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:

  # ====================================================
  # Healthchecks
  # https://github.com/healthchecks/healthchecks
  # ====================================================

  healthchecks:
    image: crazymax/healthchecks:latest
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DB=${DB:-sqlite}
      - DB_NAME=${DB_NAME:-/data/hc.sqlite}
      - DEFAULT_FROM_EMAIL
      - EMAIL_HOST
      - EMAIL_HOST_PASSWORD
      - EMAIL_HOST_USER
      - SECRET_KEY=${SECRET_KEY:-super-secret-key}
      - SITE_ROOT=${SITE_ROOT:-http://healthchecks.svc.cluster.local:18000}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL:-admin@cluster.local}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD:-admin}
    deploy:
      replicas: 1
    logging: *x-default-logging
    ports:
      - published: 18000
        target: 8000
    hostname: healthchecks.svc.cluster.local
    volumes:
      - healthchecks-data:/data

volumes:
  healthchecks-data:
